# Example configuration for Citadel Local
ignore:
  - node_modules
  - .git
  - dist
  - build
  - vendor
  - .venv
  - out_test

max_file_mb: 2
context_lines: 40

ollama:
  enabled: true
  base_url: "http://127.0.0.1:11434"
  triage_model: "llama3.2:3b"
  deep_model: "qwen3-coder:30b"
  skeptic_model: "gpt-oss:20b"
  timeout_s: 90
